spring:
  application:
    name: product-api

  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080